name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MONGODB_URI: mongodb+srv://jeffreyed:<password>@cluster0.ljdq3wb.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16' # Update de Node.js versie naar 16 of hoger

    - name: Install dependencies
      run: npm install

    - name: Run lint
      run: npm run lint

    - name: Run tests
      run: npm test
